# Generated by Django 5.2 on 2026-04-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_chatmessage_notification_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bug_type', models.CharField(choices=[('ui', 'UI Issue'), ('functionality', 'Functionality Problem'), ('performance', 'Performance Issue'), ('security', 'Security Concern'), ('payment', 'Payment Bug'), ('search', 'Search Issue'), ('mobile', 'Mobile Responsiveness'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('description', models.TextField()),
                ('steps', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('bug', 'Report a Bug'), ('feature', 'Feature Request'), ('partnership', 'Partnership'), ('other', 'Other')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
